language: python
python:
  - '3.9.1'

before_script:
  - pip install -r requirements.txt
  - touch .env
  - echo DEBUG=True >> .env
  - echo ALLOWED_HOSTS="[\"127.0.0.1:8000\"]" >> .env
  - echo CSRF_HOSTS="[\"http://127.0.0.1/\"]" >> .env
  - echo DBNAME='' >> .env

services:
  - postgresql

script:
  - python manage.py test
