language: python
python:
  - '3.9.1'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - SECRET_KEY='TEST'

services:
  - postgresql

script:
  - python manage.py test
